#ifndef _ULTRASONIC_CONFIG_H_
#define _ULTRASONIC_CONFIG_H_
///***Ultrasonic***/
//Æô¶¯ ¼ì²â
#define RCC_ULTRASONIC_TRIG1     RCC_APB2Periph_GPIOA
#define ULTRASONIC_TRIG1_GPIO    GPIOA
#define ULTRASONIC_TRIG1_PIN     GPIO_Pin_11
//·µ»Ø ÐÅºÅ
#define RCC_ULTRASONIC_ECHO1     RCC_APB2Periph_GPIOA
#define ULTRASONIC_ECHO1_GPIO    GPIOA
#define ULTRASONIC_ECHO1_PIN     GPIO_Pin_8
//Æô¶¯ ¼ì²â
#define RCC_ULTRASONIC_TRIG2     RCC_APB2Periph_GPIOA
#define ULTRASONIC_TRIG2_GPIO    GPIOA
#define ULTRASONIC_TRIG2_PIN     GPIO_Pin_10
//·µ»Ø ÐÅºÅ
#define RCC_ULTRASONIC_ECHO2     RCC_APB2Periph_GPIOA
#define ULTRASONIC_ECHO2_GPIO    GPIOA
#define ULTRASONIC_ECHO2_PIN     GPIO_Pin_9



#endif


